window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "AMDRMSDKPATH": "C:\\Program Files\\AMD\\RyzenMasterSDK\\",
  "API_HOST": "https://chateau-back-hk2hbrmct-boogysh.vercel.app",
  "APPDATA": "C:\\Users\\bugav\\AppData\\Roaming",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\LOCAL\\crashpad_1880_OXMTAEGVEHTJNEBS",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "BOOGYSH",
  "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "C:\\WINDOWS\\notepad.exe",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\bugav\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\bugav",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\bugav",
  "INIT_CWD": "D:\\D\\PROJET_N_0_Buga_VIctor\\chateau-app",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\bugav\\AppData\\Local",
  "LOGONSERVER": "\\\\BOOGYSH",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Users\\bugav\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\bugav\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\bugav\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\bugav\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\bugav\\.npm-init.js",
  "npm_config_local_prefix": "D:\\D\\PROJET_N_0_Buga_VIctor\\chateau-app",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Users\\bugav\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\bugav\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\bugav\\.npmrc",
  "npm_config_user_agent": "npm/9.1.2 node/v18.12.1 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Users\\bugav\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "D:\\D\\PROJET_N_0_Buga_VIctor\\chateau-app\\package.json",
  "npm_package_name": "chateau-app",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\bugav\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "12",
  "OneDrive": "C:\\Users\\bugav\\OneDrive",
  "OneDriveConsumer": "C:\\Users\\bugav\\OneDrive",
  "OnlineServices": "Online Services",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "D:\\D\\PROJET_N_0_Buga_VIctor\\chateau-app\\node_modules\\.bin;D:\\D\\PROJET_N_0_Buga_VIctor\\node_modules\\.bin;D:\\D\\node_modules\\.bin;D:\\node_modules\\.bin;C:\\Users\\bugav\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Users\\bugav\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\bugav\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\bugav\\AppData\\Roaming\\npm",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
  "platformcode": "M7",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD",
  "PROCESSOR_LEVEL": "25",
  "PROCESSOR_REVISION": "5000",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\bugav\\OneDrive\\Документы\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "RegionCode": "EMEA",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\WINDOWS",
  "TEMP": "C:\\Users\\bugav\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.75.0",
  "TMP": "C:\\Users\\bugav\\AppData\\Local\\Temp",
  "USERDOMAIN": "BOOGYSH",
  "USERDOMAIN_ROAMINGPROFILE": "BOOGYSH",
  "USERNAME": "bugav",
  "USERPROFILE": "C:\\Users\\bugav",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\bugav\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\bugav\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-097cf9a3ef-sock",
  "windir": "C:\\WINDOWS"
};